// the default export must be an object whose key values are
// 1-dimensional arrays comprised of objects that possess AT LEAST
// "id" and "title" property values; author, time, and link property values are optional
// property names of the default export object may be chosen at will
const bibItems = {
  printMaterials: [
    {
      id: "SK2020",
      title: "Algorithm Design Manual",
      author: "Steven Skiena",
      time: "2020",
      link: "https://www.amazon.com/Algorithm-Design-Manual-Computer-Science/dp/3030542556",
    },
  ],
  onlineMaterials: [

  ],
  sdc2: [
    {
      id: "sdc2r1",
      title: "Hypertext Transfer Protocol",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol",
    },
    {
      id: "sdc2r2",
      title: "Should you go Beyond Relational Databases?",
      author: "Team Treehouse",
      time: "",
      link: "https://blog.teamtreehouse.com/should-you-go-beyond-relational-databases",
    },
    {
      id: "sdc2r3",
      title: "Replication (Computing)",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Replication_(computing)",
    },
    {
      id: "sdc2r4",
      title: "Multi-master replication",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Multi-master_replication",
    },
    {
      id: "sdc2r5",
      title: "NDB Cluster Replication: Multi-Master and Circular Replication",
      author: "MySQL Docs",
      time: "",
      link: "https://dev.mysql.com/doc/refman/5.7/en/mysql-cluster-replication-multi-master.html",
    },
    {
      id: "sdc2r6",
      title: "Caching Strategies and How to Choose the Right One",
      author: "Code Ahoy",
      time: "",
      link: "https://codeahoy.com/2017/08/11/caching-strategies-and-how-to-choose-the-right-one/",
    },
    {
      id: "sdc2r7",
      title: "Scaling Memcache at Facebook",
      author: "Rajesh Nishtala et al.",
      time: "",
      link: "https://www.usenix.org/system/files/conference/nsdi13/nsdi13-final170_update.pdf",
    },
    {
      id: "sdc2r8",
      title: "Single point of failure",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Single_point_of_failure",
    },
    {
      id: "sdc2r9",
      title: "Amazon CloudFront Dynamic Content Delivery",
      author: "Amazon Web Services",
      time: "",
      link: "https://aws.amazon.com/cloudfront/dynamic-content/",
    },
    {
      id: "sdc2r10",
      title: "Configure Sticky Sessions for Your Classic Load Balancer",
      author: "Amazon Web Services",
      time: "",
      link: "https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-sticky-sessions.html",
    },
    {
      id: "sdc2r11",
      title: "Active-Active for Multi-Regional Resiliency",
      author: "Netflix Tech Blog",
      time: "",
      link: "https://netflixtechblog.com/active-active-for-multi-regional-resiliency-c47719f6685b",
    },
    {
      id: "sdc2r12",
      title: "Amazon EC2 High Memory Instances",
      author: "Amazon Web Services",
      time: "",
      link: "https://aws.amazon.com/ec2/instance-types/high-memory/",
    },
    {
      id: "sdc2r13",
      title: "What it takes to run Stack Overflow",
      author: "Nick Craver",
      time: "",
      link: "http://nickcraver.com/blog/2013/11/22/what-it-takes-to-run-stack-overflow",
    },
    {
      id: "sdc2r14",
      title: "What The Heck Are You Actually Using NoSQL For",
      author: "High Scalability Blog",
      time: "",
      link: "http://highscalability.com/blog/2010/12/6/what-the-heck-are-you-actually-using-nosql-for.html",
    },
  ],
  sdc3: [
    {
      id: "sdc3r1",
      title: "Google Pro Tip: Use Back-Of-The-Envelope-Calculations To Choose The Best Design",
      author: "High Scalability Blog",
      time: "",
      link: "http://highscalability.com/blog/2011/1/26/google-pro-tip-use-back-of-the-envelope-calculations-to-choo.html",
    },
    {
      id: "sdc3r2",
      title: "System design primer",
      author: "Donne Martin",
      time: "",
      link: "https://github.com/donnemartin/system-design-primer",
    },
    {
      id: "sdc3r3",
      title: "Latency Numbers Every Programmer Should Know",
      author: "Colin Scott",
      time: "",
      link: "https://colin-scott.github.io/personal_website/research/interactive_latency.html",
    },
    {
      id: "sdc3r4",
      title: "Amazon Compute Service Level Agreement",
      author: "Amazon Web Services",
      time: "",
      link: "https://aws.amazon.com/compute/sla/",
    },
    {
      id: "sdc3r5",
      title: "Compute Engine Service Level Agreement (SLA)",
      author: "Google Cloud",
      time: "",
      link: "https://cloud.google.com/compute/sla",
    },
    {
      id: "sdc3r6",
      title: "SLA summary for Azure services",
      author: "Microsoft Azure",
      time: "",
      link: "https://azure.microsoft.com/en-us/support/legal/sla/summary/",
    },
  ],
  sdc5: [
    {
      id: "sdc5r1",
      title: "Rate-limiting strategies and techniques",
      author: "Google Cloud",
      time: "",
      link: "https://cloud.google.com/solutions/rate-limiting-strategies-techniques",
    },
    {
      id: "sdc5r2",
      title: "Twitter rate limits",
      author: "Twitter Docs",
      time: "",
      link: "https://developer.twitter.com/en/docs/basics/rate-limits",
    },
    {
      id: "sdc5r3",
      title: "Google docs usage limits",
      author: "Google Docs",
      time: "",
      link: "https://developers.google.com/docs/api/limits",
    },
    {
      id: "sdc5r4",
      title: "IBM microservices",
      author: "IBM",
      time: "",
      link: "https://www.ibm.com/cloud/learn/microservices",
    },
    {
      id: "sdc5r5",
      title: "Throttle API requests for better throughput",
      author: "Amazon Web Services",
      time: "",
      link: "https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-request-throttling.html",
    },
    {
      id: "sdc5r6",
      title: "Stripe rate limiters",
      author: "Stripe",
      time: "",
      link: "https://stripe.com/blog/rate-limiters",
    },
    {
      id: "sdc5r7",
      title: "Shopify REST Admin API rate limits",
      author: "Shopify",
      time: "",
      link: "https://help.shopify.com/en/api/reference/rest-admin-api-rate-limits",
    },
    {
      id: "sdc5r8",
      title: "Better Rate Limiting With Redis Sorted Sets",
      author: "Peter Hayes",
      time: "",
      link: "https://engineering.classdojo.com/blog/2015/02/06/rolling-rate-limiter/",
    },
    {
      id: "sdc5r9",
      title: "System Design — Rate limiter and Data modelling",
      author: "Sai Sandeep Mopuri",
      time: "",
      link: "https://medium.com/@saisandeepmopuri/system-design-rate-limiter-and-data-modelling-9304b0d18250",
    },
    {
      id: "sdc5r10",
      title: "How we built rate limiting capable of scaling to millions of domains",
      author: "Cloudflare Blog",
      time: "",
      link: "https://blog.cloudflare.com/counting-things-a-lot-of-different-things/",
    },
    {
      id: "sdc5r11",
      title: "Redis website",
      author: "Redis",
      time: "",
      link: "https://redis.io/",
    },
    {
      id: "sdc5r12",
      title: "Lyft rate limiting",
      author: "Lyft",
      time: "",
      link: "https://github.com/lyft/ratelimit",
    },
    {
      id: "sdc5r13",
      title: "Scaling your API with rate limiters",
      author: "Paul Tarjan",
      time: "",
      link: "https://gist.github.com/ptarjan/e38f45f2dfe601419ca3af937fff574d#request-rate-limiter",
    },
    {
      id: "sdc5r14",
      title: "What is edge computing",
      author: "Cloudflare Learning",
      time: "",
      link: "https://www.cloudflare.com/learning/serverless/glossary/what-is-edge-computing/",
    },
    {
      id: "sdc5r15",
      title: "Rate Limit Requests with Iptables",
      author: "Programster Blog",
      time: "",
      link: "https://blog.programster.org/rate-limit-requests-with-iptables",
    },
    {
      id: "sdc5r16",
      title: "OSI model",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/OSI_model#Layer_architecture",
    },
  ],
  sdc6: [
    {
      id: "sdc6r1",
      title: "Consistent hashing",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Consistent_hashing",
    },
    {
      id: "sdc6r2",
      title: "Consistent Hashing",
      author: "Tom White",
      time: "",
      link: "https://tom-e-white.com/2007/11/consistent-hashing.html",
    },
    {
      id: "sdc6r3",
      title: "Dynamo: Amazon's Highly Available Key- value Store",
      author: "",
      time: "",
      link: "https://www.allthingsdistributed.com/files/amazon-dynamo-sosp2007.pdf",
    },
    {
      id: "sdc6r4",
      title: "Cassandra - A Decentralized Structured Storage System",
      author: "",
      time: "",
      link: "http://www.cs.cornell.edu/Projects/ladis2009/papers/Lakshman-ladis2009.PDF",
    },
    {
      id: "sdc6r5",
      title: "How Discord Scaled Elixir to 5,000,000 Concurrent Users",
      author: "",
      time: "",
      link: "https://blog.discord.com/scaling-elixir-f9b8e1e7c29b",
    },
    {
      id: "sdc6r6",
      title: "CS168: The Modern Algorithmic Toolbox Lecture #1: Introduction and Consistent Hashing",
      author: "",
      time: "",
      link: "http://theory.stanford.edu/~tim/s16/l/l1.pdf",
    },
    {
      id: "sdc6r7",
      title: "Maglev: A Fast and Reliable Software Network Load Balancer",
      author: "",
      time: "",
      link: "https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/44824.pdf",
    },
  ],
  sdc7: [
    {
      id: "sdc7r1",
      title: "Amazon DynamoDB",
      author: "Amazon Web Services",
      time: "",
      link: "https://aws.amazon.com/dynamodb/",
    },
    {
      id: "sdc7r2",
      title: "memcached",
      author: "memcached",
      time: "",
      link: "https://memcached.org/",
    },
    {
      id: "sdc7r3",
      title: "Redis",
      author: "Redis",
      time: "",
      link: "https://redis.io/",
    },
    {
      id: "sdc7r4",
      title: "Dynamo: Amazon's Highly Available Key-value Store",
      author: "All Things Distributed",
      time: "",
      link: "https://www.allthingsdistributed.com/files/amazon-dynamo-sosp2007.pdf",
    },
    {
      id: "sdc7r5",
      title: "Cassandra",
      author: "Cassandra",
      time: "",
      link: "https://cassandra.apache.org/",
    },
    {
      id: "sdc7r6",
      title: "Bigtable: A Distributed Storage System for Structured Data",
      author: "Fay Change et al.",
      time: "",
      link: "https://static.googleusercontent.com/media/research.google.com/en//archive/bigtable-osdi06.pdf",
    },
    {
      id: "sdc7r7",
      title: "Merkle tree",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Merkle_tree",
    },
    {
      id: "sdc7r8",
      title: "Cassandra architecture",
      author: "Cassandra",
      time: "",
      link: "https://cassandra.apache.org/doc/latest/architecture/",
    },
    {
      id: "sdc7r9",
      title: "SStable",
      author: "Ilya Grigorik",
      time: "",
      link: "https://www.igvita.com/2012/02/06/sstable-and-log-structured-storage-leveldb/",
    },
    {
      id: "sdc7r10",
      title: "Bloom filter",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Bloom_filter",
    },
  ],
  sdc8: [
    {
      id: "sdc8r1",
      title: "Universally unique identifier",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Universally_unique_identifier",
    },
    {
      id: "sdc8r2",
      title: "Ticket Servers: Distributed Unique Primary Keys on the Cheap",
      author: "Flickr",
      time: "",
      link: "https://code.flickr.net/2010/02/08/ticket-servers-distributed-unique-primary-keys-on-the-cheap/",
    },
    {
      id: "sdc8r3",
      title: "Announcing Snowflake",
      author: "Twitter Blog",
      time: "",
      link: "https://blog.twitter.com/engineering/en_us/a/2010/announcing-snowflake.html",
    },
    {
      id: "sdc8r4",
      title: "Network time protocol",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Network_Time_Protocol",
    },
  ],
  sdc9: [
    {
      id: "sdc9r1",
      title: "A RESTful Tutorial",
      author: "Todd Fredrich",
      time: "",
      link: "https://www.restapitutorial.com/index.html",
    },
    {
      id: "sdc9r2",
      title: "Bloom filter",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Bloom_filter",
    },
  ],
  sdc10: [
    {
      id: "sdc10r1",
      title: "Search Web Archives",
      author: "US Library of Congress",
      time: "",
      link: "https://www.loc.gov/websites/",
    },
    {
      id: "sdc10r2",
      title: "EU Web Archive",
      author: "Publications Office of the European Union",
      time: "",
      link: "http://data.europa.eu/webarchive",
    },
    {
      id: "sdc10r3",
      title: "Digimarc Homepage",
      author: "Digimarc",
      time: "",
      link: "https://www.digimarc.com/products/digimarc-services/piracy-intelligence",
    },
    {
      id: "sdc10r4",
      title: "Mercator: A scalable, extensible web crawler World Wide Web, 2 (4) (1999), pp. 219-229",
      author: "Allan Heydon and Marc Najork",
      time: "",
      link: "https://courses.cs.washington.edu/courses/cse454/15wi/papers/mercator.pdf",
    },
    {
      id: "sdc10r5",
      title: "Web Crawling. ",
      author: "Christopher Olston and Marc Najork",
      time: "",
      link: "http://infolab.stanford.edu/~olston/publications/crawling_survey.pdf",
    },
    {
      id: "sdc10r6",
      title: "29% Of Sites Face Duplicate Content Issues",
      author: "Search Engine Land",
      time: "",
      link: "https://searchengineland.com/study-29-of-sites-face-duplicate-content-issues-80-arent-using-schema-org-microdata-232870",
    },
    {
      id: "sdc10r7",
      title: "Fingerprinting by Random Polynomials",
      author: "Michael O. Rabin",
      time: "1981",
      link: "http://www.xmailserver.org/rabin.pdf",
    },
    {
      id: "sdc10r8",
      title: "Space/Time Trade-offs in Hash Coding with Allowable Errors",
      author: "Burton H. Bloom",
      time: "1970",
      link: "https://cs.pwr.edu.pl/cichon/2021_22_a/BigData/Bloom.pdf",
    },
    {
      id: "sdc10r9",
      title: "Web Crawling: Introduction to Information Retrieval",
      author: "Donald J. Patterson",
      time: "",
      link: "https://www.ics.uci.edu/~lopes/teaching/cs221W12/slides/Lecture05.pdf",
    },
    {
      id: "sdc10r10",
      title: "The PageRank Citation Ranking: Bringing Order to the Web",
      author: "Larry Page and Sergey Brin",
      time: "1998",
      link: "http://ilpubs.stanford.edu:8090/422/1/1999-66.pdf",
    },
    {
      id: "sdc10r11",
      title: "Space/Time Trade-offs in Hash Coding with Allowable Errors",
      author: "Burton H. Bloom",
      time: "",
      link: "https://cs.pwr.edu.pl/cichon/2021_22_a/BigData/Bloom.pdf",
    },
    {
      id: "sdc10r12",
      title: "Google Dynamic Rendering: ",
      author: "Google Search Central",
      time: "",
      link: "https://developers.google.com/search/docs/guides/dynamic-rendering",
    },
    {
      id: "sdc10r13",
      title: "Tracking Web Spam with Hidden Style Similarity",
      author: "Tanguy Urvoy et al.",
      time: "2006",
      link: "http://airweb.cse.lehigh.edu/2006/urvoy.pdf",
    },
    {
      id: "sdc10r14",
      title: "IRLbot: Scaling to 6 Billion Pages and Beyond",
      author: "Hsin-Tsang Lee et al.",
      time: "2008",
      link: "https://irl.cs.tamu.edu/people/hsin-tsang/papers/www2008.pdf",
    },
  ],
  sdc11: [
    {
      id: "sdc11r1",
      title: "Twilio SMS",
      author: "Twilio",
      time: "",
      link: "https://www.twilio.com/sms",
    },
    {
      id: "sdc11r2",
      title: "Nexmo SMS",
      author: "Nexmo",
      time: "",
      link: "https://www.nexmo.com/products/sms",
    },
    {
      id: "sdc11r3",
      title: "Sendgrid",
      author: "Sendgrid",
      time: "",
      link: "https://sendgrid.com/",
    },
    {
      id: "sdc11r4",
      title: "Mailchimp",
      author: "Mailchimp",
      time: "",
      link: "https://mailchimp.com/",
    },
    {
      id: "sdc11r5",
      title: "You Cannot Have Exactly-Once Delivery",
      author: "Tyler Treat",
      time: "",
      link: "https://bravenewgeek.com/you-cannot-have-exactly-once-delivery/",
    },
    {
      id: "sdc11r6",
      title: "Security in Push Notifications",
      author: "IBM",
      time: "",
      link: "https://cloud.ibm.com/docs/services/mobilepush?topic=mobile-pushnotification-security-in-push-notifications",
    },
    {
      id: "sdc11r7",
      title: "Key metrics for RabbitMQ monitoring",
      author: "Data Dog",
      time: "",
      link: "https://www.datadoghq.com/blog/rabbitmq-monitoring",
    },
  ],
  sdc12: [
    {
      id: "sdc12r1",
      title: "How News Feed Works",
      author: "Facebook",
      time: "",
      link: "https://www.facebook.com/help/327131014036297/",
    },
    {
      id: "sdc12r2",
      title: "Friend of Friend recommendations Neo4j and SQL Sever",
      author: "Geeks with Blogs",
      time: "",
      link: "http://geekswithblogs.net/brendonpage/archive/2015/10/26/friend-of-friend-recommendations-with-neo4j.aspx",
    },
  ],
  sdc13: [
    {
      id: "sdc13r1",
      title: "Erlang at Facebook",
      author: "Facebook",
      time: "",
      link: "https://www.erlang-factory.com/upload/presentations/31/EugeneLetuchy-ErlangatFacebook.pdf",
    },
    {
      id: "sdc13r2",
      title: "Messenger and WhatsApp process 60 billion messages a day",
      author: "The Verge",
      time: "",
      link: "https://www.theverge.com/2016/4/12/11415198/facebook-messenger-whatsapp-number-messages-vs-sms-f8-2016",
    },
    {
      id: "sdc13r3",
      title: "Long tail",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Long_tail",
    },
    {
      id: "sdc13r4",
      title: "The Underlying Technology of Messages",
      author: "Facebook",
      time: "",
      link: "https://www.facebook.com/notes/facebook-engineering/the-underlying-technology-of-messages/454991608919/",
    },
    {
      id: "sdc13r5",
      title: "How Discord Stores Billions of Messages",
      author: "Discord",
      time: "",
      link: "https://blog.discordapp.com/how-discord-stores-billions-of-messages-7fa6ec7ee4c7",
    },
    {
      id: "sdc13r6",
      title: "Announcing Snowflake",
      author: "Twitter Blog",
      time: "",
      link: "https://blog.twitter.com/engineering/en_us/a/2010/announcing-snowflake.html",
    },
    {
      id: "sdc13r7",
      title: "Apache ZooKeeper",
      author: "Apache ZooKeeper",
      time: "",
      link: "https://zookeeper.apache.org/",
    },
    {
      id: "sdc13r8",
      title: "From nothing: the evolution of WeChat background system (Article in Chinese)",
      author: "InfoQ",
      time: "",
      link: "https://www.infoq.cn/article/the-road-of-the-growth-weixin-background",
    },
    {
      id: "sdc13r9",
      title: "End-to-end encryption",
      author: "WhatsApp",
      time: "",
      link: "https://faq.whatsapp.com/en/android/28030015/",
    },
    {
      id: "sdc13r10",
      title: "Flannel: An Application-Level Edge Cache to Make Slack Scale",
      author: "Slack Engineering",
      time: "",
      link: "https://slack.engineering/flannel-an-application-level-edge-cache-to-make-slack-scale-b8a6400e2f6b",
    },
  ],
  sdc14: [
    {
      id: "sdc14r1",
      title: "The Life of a Typeahead Query",
      author: "Facebook",
      time: "",
      link: "https://www.facebook.com/notes/facebook-engineering/the-life-of-a-typeahead-query/389105248919/",
    },
    {
      id: "sdc14r2",
      title: "How We Built Prefixy: A Scalable Prefix Search Service for Powering Autocomplete",
      author: "Prefixy Team",
      time: "",
      link: "https://medium.com/@prefixyteam/how-we-built-prefixy-a-scalable-prefix-search-service-for-powering-autocomplete-c20f98e2eff1",
    },
    {
      id: "sdc14r3",
      title: "Prefix Hash Tree An Indexing Data Structure over Distributed Hash Tables",
      author: "Sriram Ramabhadran",
      time: "",
      link: "https://people.eecs.berkeley.edu/~sylvia/papers/pht.pdf",
    },
    {
      id: "sdc14r4",
      title: "MongoDB wikipedia",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/MongoDB",
    },
    {
      id: "sdc14r5",
      title: "Unicode frequently asked questions",
      author: "Unicode",
      time: "",
      link: "https://www.unicode.org/faq/basic_q.html",
    },
    {
      id: "sdc14r6",
      title: "Apache hadoop",
      author: "Apache Hadoop",
      time: "",
      link: "https://hadoop.apache.org/",
    },
    {
      id: "sdc14r7",
      title: "Spark streaming",
      author: "Apache Spark",
      time: "",
      link: "https://spark.apache.org/streaming/",
    },
    {
      id: "sdc14r8",
      title: "Apache storm",
      author: "Apache Storm",
      time: "",
      link: "https://storm.apache.org/",
    },
    {
      id: "sdc14r9",
      title: "Apache kafka",
      author: "Apache Kafka",
      time: "",
      link: "https://kafka.apache.org/documentation/",
    },
  ],
  sdc15: [
    {
      id: "sdc15r1",
      title: "YouTube by the numbers",
      author: "Omnicore",
      time: "",
      link: "https://www.omnicoreagency.com/youtube-statistics/",
    },
    {
      id: "sdc15r2",
      title: "2019 YouTube Demographics",
      author: "HubSpot",
      time: "",
      link: "https://blog.hubspot.com/marketing/youtube-demographics",
    },
    {
      id: "sdc15r3",
      title: "Cloudfront Pricing",
      author: "Amazon Web Services",
      time: "",
      link: "https://aws.amazon.com/cloudfront/pricing/",
    },
    {
      id: "sdc15r4",
      title: "Netflix on AWS",
      author: "Amazon Web Services",
      time: "",
      link: "https://aws.amazon.com/solutions/case-studies/netflix/",
    },
    {
      id: "sdc15r5",
      title: "Akamai homepage",
      author: "Akamai",
      time: "",
      link: "https://www.akamai.com/",
    },
    {
      id: "sdc15r6",
      title: "Binary large object",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Binary_large_object",
    },
    {
      id: "sdc15r7",
      title: "Here's What You Need to Know About Streaming Protocols",
      author: "Dacast",
      time: "",
      link: "https://www.dacast.com/blog/streaming-protocols/",
    },
    {
      id: "sdc15r8",
      title: "SVE: Distributed Video Processing at Facebook Scale",
      author: "Princeton CS",
      time: "",
      link: "https://www.cs.princeton.edu/~wlloyd/papers/sve-sosp17.pdf",
    },
    {
      id: "sdc15r9",
      title: "Weibo video processing architecture (in Chinese)",
      author: "Upyun",
      time: "",
      link: "https://www.upyun.com/opentalk/399.html",
    },
    {
      id: "sdc15r10",
      title: "Delegate access with a shared access signature",
      author: "Microsoft",
      time: "",
      link: "https://docs.microsoft.com/en-us/rest/api/storageservices/delegate-access-with-shared-access-signature",
    },
    {
      id: "sdc15r11",
      title: "YouTube scalability talk by early YouTube employee",
      author: "YouTube",
      time: "",
      link: "https://www.youtube.com/watch?v=w5WVu624fY8",
    },
    {
      id: "sdc15r12",
      title: "Understanding the characteristics of internet short video sharing: A youtube-based measurement study",
      author: "Xu Cheng et al.",
      time: "",
      link: "https://arxiv.org/pdf/0707.3670.pdf",
    },
    {
      id: "sdc15r13",
      title: "Content Popularity for Open Connect",
      author: "Netflix Tech Blog",
      time: "",
      link: "https://netflixtechblog.com/content-popularity-for-open-connect-b86d56f613b",
    },
  ],
  sdc16: [
    {
      id: "sdc16r1",
      title: "Google Drive",
      author: "",
      time: "",
      link: "https://www.google.com/drive/",
    },
    {
      id: "sdc16r2",
      title: "Upload file data",
      author: "Google Docs",
      time: "",
      link: "https://developers.google.com/drive/api/v2/manage-uploads",
    },
    {
      id: "sdc16r3",
      title: "Amazon S3",
      author: "Amazon Web Services",
      time: "",
      link: "https://aws.amazon.com/s3",
    },
    {
      id: "sdc16r4",
      title: "Differential Synchronization",
      author: "Neil Fraser",
      time: "",
      link: "https://neil.fraser.name/writing/sync/",
    },
    {
      id: "sdc16r5",
      title: "Differential Synchronization YouTube talk",
      author: "Neil Fraser",
      time: "",
      link: "https://www.youtube.com/watch?v=S2Hp_1jqpY8",
    },
    {
      id: "sdc16r6",
      title: "How We've Scaled Dropbox",
      author: "Kevin Modzelewski",
      time: "",
      link: "https://youtu.be/PE4gwstWhmc",
    },
    {
      id: "sdc16r7",
      title: "The rsync algorithm",
      author: "Andrew Tridgell and Paul Mackerras",
      time: "",
      link: "https://www.andrew.cmu.edu/course/15-749/READINGS/required/cas/tridgell96.pdf",
    },
    {
      id: "sdc16r8",
      title: "Librsync",
      author: "Martin Pool et al.",
      time: "",
      link: "https://github.com/librsync/librsync",
    },
    {
      id: "sdc16r9",
      title: "ACID",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/ACID",
    },
    {
      id: "sdc16r10",
      title: "Dropbox security white paper",
      author: "Dropbox",
      time: "",
      link: "https://www.dropbox.com/static/business/resources/Security_Whitepaper.pdf",
    },
    {
      id: "sdc16r11",
      title: "Amazon S3 Glacier",
      author: "Amazon Web Services",
      time: "",
      link: "https://aws.amazon.com/glacier/faqs/",
    },
  ],
  sdc17: [
    {
      id: "sdc17r1",
      title: "Yelp Homepage",
      author: "",
      time: "",
      link: "https://www.yelp.com/",
    },
    {
      id: "sdc17r2",
      title: "Map tiles by Stamen Design",
      author: "Stamen Design",
      time: "",
      link: "http://maps.stamen.com/",
    },
    {
      id: "sdc17r3",
      title: "OpenStreetMap Homepage",
      author: "OpenStreetMap",
      time: "",
      link: "https://www.openstreetmap.org",
    },
    {
      id: "sdc17r4",
      title: "GDPR (Data Protection Regulation)",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/General_Data_Protection_Regulation",
    },
    {
      id: "sdc17r5",
      title: "CCPA (California Consumer Privacy Act)",
      author: "",
      time: "",
      link: "https://en.wikipedia.org/wiki/California_Consumer_Privacy_Act",
    },
    {
      id: "sdc17r6",
      title: "Pagination in the REST API",
      author: "Atlassian",
      time: "",
      link: "https://developer.atlassian.com/server/confluence/pagination-in-the-rest-api/",
    },
    {
      id: "sdc17r7",
      title: "Google places API",
      author: "Google Docs",
      time: "",
      link: "https://developers.google.com/maps/documentation/places/web-service/search",
    },
    {
      id: "sdc17r8",
      title: "Yelp business endpoints",
      author: "Yelp",
      time: "",
      link: "https://www.yelp.com/developers/documentation/v3/business_search",
    },
    {
      id: "sdc17r9",
      title: "Regions and Zones",
      author: "Amazon Web Services",
      time: "",
      link: "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html",
    },
    {
      id: "sdc17r10",
      title: "Redis GEOHASH",
      author: "Redis",
      time: "",
      link: "https://redis.io/commands/GEOHASH",
    },
    {
      id: "sdc17r11",
      title: "POSTGIS",
      author: "POSTGIS",
      time: "",
      link: "https://postgis.net/",
    },
    {
      id: "sdc17r12",
      title: "Cartesian tiers",
      author: "Patrick O'Leary",
      time: "",
      link: "http://www.nsshutdown.com/projects/lucene/whitepaper/locallucene_v2.html",
    },
    {
      id: "sdc17r13",
      title: "R-tree",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/R-tree",
    },
    {
      id: "sdc17r14",
      title: "Global map in a Geographic Coordinate Reference System",
      author: "Earth Lab",
      time: "",
      link: "https://www.earthdatascience.org/courses/use-data-open-source-python/intro-vector-data-python/spatial-data-vector-shapefiles/geographic-vs-projected-coordinate-reference-systems-python/",
    },
    {
      id: "sdc17r15",
      title: "Base32",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Base32",
    },
    {
      id: "sdc17r16",
      title: "Geohash grid aggregation",
      author: "Elastic",
      time: "",
      link: "https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-aggregations-bucket-geohashgrid-aggregation.html",
    },
    {
      id: "sdc17r17",
      title: "Geohash",
      author: "Movable Type Scripts",
      time: "",
      link: "https://www.movable-type.co.uk/scripts/geohash.html",
    },
    {
      id: "sdc17r18",
      title: "Quadtree",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Quadtree",
    },
    {
      id: "sdc17r19",
      title: "How many leaves has a quadtree",
      author: "Stack Overflow",
      time: "",
      link: "https://stackoverflow.com/questions/35976444/how-many-leaves-has-a-quadtree",
    },
    {
      id: "sdc17r20",
      title: "Blue green deployment",
      author: "Martin Fowler",
      time: "",
      link: "https://martinfowler.com/bliki/BlueGreenDeployment.html",
    },
    {
      id: "sdc17r21",
      title: "Improved Location Caching with Quadtrees",
      author: "Yext Engineering Blog",
      time: "",
      link: "https://engblog.yext.com/post/geolocation-caching",
    },
    {
      id: "sdc17r22",
      title: "S2",
      author: "S2 Geometry Homepage",
      time: "",
      link: "https://s2geometry.io/",
    },
    {
      id: "sdc17r23",
      title: "Hilbert curve",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Hilbert_curve",
    },
    {
      id: "sdc17r24",
      title: "Hilbert mapping",
      author: "",
      time: "",
      link: "http://bit-player.org/extras/hilbert/hilbert-mapping.html",
    },
    {
      id: "sdc17r25",
      title: "Geo-fence",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Geo-fence",
    },
    {
      id: "sdc17r26",
      title: "Region cover",
      author: "S2 Geometry",
      time: "",
      link: "https://s2.sidewalklabs.com/regioncoverer/",
    },
    {
      id: "sdc17r27",
      title: "Bing Maps Tile System",
      author: "Microsoft",
      time: "",
      link: "https://docs.microsoft.com/en-us/bingmaps/articles/bing-maps-tile-system?redirectedfrom=MSDN",
    },
    {
      id: "sdc17r28",
      title: "MongoDB",
      author: "MongoDB",
      time: "",
      link: "https://docs.mongodb.com/manual/tutorial/build-a-2d-index/",
    },
    {
      id: "sdc17r29",
      title: "Geospatial Indexing: The 10 Million QPS Redis Architecture Powering Lyft",
      author: "Redis",
      time: "",
      link: "https://www.youtube.com/watch?v=cSFWlF96Sds&t=2155s",
    },
    {
      id: "sdc17r30",
      title: "Geo Shape Type",
      author: "Elastic",
      time: "",
      link: "https://www.elastic.co/guide/en/elasticsearch/reference/1.6/mapping-geo-shape-type.html",
    },
    {
      id: "sdc17r31",
      title: "Geosharded Recommendations Part 1: Sharding Approach",
      author: "Frank Ren",
      time: "",
      link: "https://medium.com/tinder-engineering/geosharded-recommendations-part-1-sharding-approach-d5d54e0ec77a",
    },
    {
      id: "sdc17r32",
      title: "Get the last known location",
      author: "Android Docs",
      time: "",
      link: "https://developer.android.com/training/location/retrieve-current#Challenges",
    },
  ],
  sdc18: [
    {
      id: "sdc18r1",
      title: "Facebook Launches 'Nearby Friends'",
      author: "Josh Constine",
      time: "",
      link: "https://techcrunch.com/2014/04/17/facebook-nearby-friends/",
    },
    {
      id: "sdc18r2",
      title: "Redis Pub/Sub",
      author: "Redis",
      time: "",
      link: "https://redis.io/topics/pubsub",
    },
    {
      id: "sdc18r3",
      title: "Redis Pub/Sub under the hood",
      author: "Jim Fisher",
      time: "",
      link: "https://making.pusher.com/redis-pubsub-under-the-hood/",
    },
    {
      id: "sdc18r4",
      title: "etcd Homepage",
      author: "etcd",
      time: "",
      link: "https://etcd.io/",
    },
    {
      id: "sdc18r5",
      title: "Apache Zookeeper Homepage",
      author: "Apache Zookeeper",
      time: "",
      link: "https://zookeeper.apache.org/",
    },
    {
      id: "sdc18r6",
      title: "Consistent hashing",
      author: "Toptal",
      time: "",
      link: "https://www.toptal.com/big-data/consistent-hashing",
    },
    {
      id: "sdc18r7",
      title: "OpenStreetMap Homepage",
      author: "OpenStreetMap",
      time: "",
      link: "https://www.openstreetmap.org",
    },
    {
      id: "sdc18r8",
      title: "Erlang Homepage",
      author: "Erlang",
      time: "",
      link: "https://www.erlang.org/",
    },
    {
      id: "sdc18r9",
      title: "Elixir Homepage",
      author: "Elixir",
      time: "",
      link: "https://elixir-lang.org/",
    },
    {
      id: "sdc18r10",
      title: "A brief introduction to BEAM",
      author: "Erlang",
      time: "",
      link: "https://www.erlang.org/blog/a-brief-beam-primer/",
    },
    {
      id: "sdc18r11",
      title: "OTP",
      author: "Erlang",
      time: "",
      link: "https://www.erlang.org/doc/design_principles/des_princ.html",
    },
  ],
  sdc19: [
    {
      id: "sdc19r1",
      title: "Google Maps Homepage",
      author: "",
      time: "",
      link: "https://developers.google.com/maps?hl=en_US",
    },
    {
      id: "sdc19r2",
      title: "Google Maps Platform",
      author: "",
      time: "",
      link: "https://cloud.google.com/maps-platform/",
    },
    {
      id: "sdc19r3",
      title: "Stamen Design",
      author: "",
      time: "",
      link: "https://maps.stamen.com",
    },
    {
      id: "sdc19r4",
      title: "OpenStreetMap Homepage",
      author: "OpenStreetMap",
      time: "",
      link: "https://www.openstreetmap.org",
    },
    {
      id: "sdc19r5",
      title: "Prototyping a Smoother Map",
      author: "Antin Harasymiv",
      time: "",
      link: "https://medium.com/google-design/google-maps-cb0326d165f5",
    },
    {
      id: "sdc19r6",
      title: "Mercator projection",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Mercator_projection",
    },
    {
      id: "sdc19r7",
      title: "Peirce quincuncial projection",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Peirce_quincuncial_projection",
    },
    {
      id: "sdc19r8",
      title: "Gall–Peters projection",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Gall–Peters_projection",
    },
    {
      id: "sdc19r9",
      title: "Winkel tripel projection",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Winkel_tripel_projection",
    },
    {
      id: "sdc19r10",
      title: "Address geocoding",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Address_geocoding",
    },
    {
      id: "sdc19r11",
      title: "Geohashing",
      author: "Kousik Nath",
      time: "",
      link: "https://kousiknath.medium.com/system-design-design-a-geo-spatial-index-for-real-time-location-search-10968fe62b9c",
    },
    {
      id: "sdc19r12",
      title: "HTTP keep-alive",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/HTTP_persistent_connection",
    },
    {
      id: "sdc19r13",
      title: "Google Directions API",
      author: "",
      time: "",
      link: "https://developers.google.com/maps/documentation/directions/start?hl=en_US",
    },
    {
      id: "sdc19r14",
      title: "Adjacency list",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Adjacency_list",
    },
    {
      id: "sdc19r15",
      title: "CAP theorem",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/CAP_theorem",
    },
    {
      id: "sdc19r16",
      title: "Routing Tiles",
      author: "Valhalla",
      time: "",
      link: "https://valhalla.readthedocs.io/en/latest/mjolnir/why_tiles/",
    },
    {
      id: "sdc19r17",
      title: "ETAs with GNNs",
      author: "DeepMind",
      time: "",
      link: "https://deepmind.com/blog/article/traffic-prediction-with-advanced-graph-neural-networks",
    },
    {
      id: "sdc19r18",
      title: "Google Maps 101: How AI helps predict traffic and determine routes",
      author: "",
      time: "",
      link: "https://blog.google/products/maps/google-maps-101-how-ai-helps-predict-traffic-and-determine-routes/",
    },
  ],
  sdc20: [
    {
      id: "sdc20r1",
      title: "Queue Length Limit",
      author: "RabbitMQ",
      time: "",
      link: "https://www.rabbitmq.com/maxlength.html",
    },
    {
      id: "sdc20r2",
      title: "Apache ZooKeeper",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Apache_ZooKeeper",
    },
    {
      id: "sdc20r3",
      title: "etcd Homepage",
      author: "etcd",
      time: "",
      link: "https://etcd.io/",
    },
    {
      id: "sdc20r4",
      title: "Comparison of disk and memory performance",
      author: "ACM",
      time: "",
      link: "https://deliveryimages.acm.org/10.1145/1570000/1563874/jacobs3.jpg",
    },
    {
      id: "sdc20r5",
      title: "Cyclic redundancy check",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Cyclic_redundancy_check",
    },
    {
      id: "sdc20r6",
      title: "Push vs. pull",
      author: "Apache Kafka",
      time: "",
      link: "https://kafka.apache.org/documentation/#design_pull",
    },
    {
      id: "sdc20r7",
      title: "Kafka 2.0 Documentation",
      author: "Apache Kafka",
      time: "",
      link: "https://kafka.apache.org/20/documentation.html#consumerconfigs",
    },
    {
      id: "sdc20r8",
      title: "Kafka No Longer Requires ZooKeeper",
      author: "",
      time: "",
      link: "https://towardsdatascience.com/kafka-no-longer-requires-zookeeper-ebfbf3862104",
    },
    {
      id: "sdc20r9",
      title: "'Replication' in Designing Data-Intensive Applications",
      author: "Martin Kleppmann",
      time: "",
      link: "https://www.oreilly.com/library/view/designing-data-intensive-applications/9781491903063/ch05.html",
    },
    {
      id: "sdc20r10",
      title: "ISR in Apache Kafka",
      author: "cloudkarafka",
      time: "",
      link: "https://www.cloudkarafka.com/blog/what-does-in-sync-in-apache-kafka-really-mean.html",
    },
    {
      id: "sdc20r11",
      title: "Apache Kafka allow consumers fetch from closest replica",
      author: "Apache",
      time: "",
      link: "https://cwiki.apache.org/confluence/display/KAFKA/KIP-392%3A+Allow+consumers+to+fetch+from+closest+replica",
    },
    {
      id: "sdc20r12",
      title: "Hands-free Kafka Replication",
      author: "Confluent",
      time: "",
      link: "https://www.confluent.io/blog/hands-free-kafka-replication-a-lesson-in-operational-simplicity/",
    },
    {
      id: "sdc20r13",
      title: "Kafka high watermark",
      author: "ronginx Blog",
      time: "",
      link: "https://rongxinblog.wordpress.com/2016/07/29/kafka-high-watermark/",
    },
    {
      id: "sdc20r14",
      title: "Kafka mirroring",
      author: "Apache",
      time: "",
      link: "https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=27846330",
    },
    {
      id: "sdc20r15",
      title: "Message filtering in RocketMQ",
      author: "",
      time: "",
      link: "https://partners-intl.aliyun.com/help/doc-detail/29543.htm",
    },
    {
      id: "sdc20r16",
      title: "Scheduled messages and delayed messages in Apache RocketMQ",
      author: "",
      time: "",
      link: "https://partners-intl.aliyun.com/help/doc-detail/43349.htm",
    },
    {
      id: "sdc20r17",
      title: "Hashed and hierarchical timing wheels",
      author: "Columbia CS",
      time: "",
      link: "https://www.cs.columbia.edu/~nahum/w6998/papers/sosp87-timing-wheels.pdf",
    },
    {
      id: "sdc20r18",
      title: "Advanced Message Queuing Protocol",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Advanced_Message_Queuing_Protocol",
    },
    {
      id: "sdc20r19",
      title: "Kafka protocol guide",
      author: "Apache Kafka",
      time: "",
      link: "https://kafka.apache.org/protocol",
    },
  ],
  sdc21: [
    {
      id: "sdc21r1",
      title: "Datadog Homepage",
      author: "",
      time: "",
      link: "https://www.datadoghq.com/",
    },
    {
      id: "sdc21r2",
      title: "Splunk Homepage",
      author: "",
      time: "",
      link: "https://www.splunk.com/",
    },
    {
      id: "sdc21r3",
      title: "Elastic stack",
      author: "Elastic",
      time: "",
      link: "https://www.elastic.co/elastic-stack",
    },
    {
      id: "sdc21r4",
      title: "Dapper, a Large-Scale Distributed Systems Tracing Infrastructure",
      author: "Google Research",
      time: "",
      link: "https://research.google/pubs/pub36356/",
    },
    {
      id: "sdc21r5",
      title: "Distributed Systems Tracing with Zipkin",
      author: "Twitter Blog",
      time: "",
      link: "https://blog.twitter.com/engineering/en_us/a/2012/distributed-systems-tracing-with-zipkin.html",
    },
    {
      id: "sdc21r6",
      title: "Prometheus Introduction",
      author: "Prometheus",
      time: "",
      link: "https://prometheus.io/docs/introduction/overview/",
    },
    {
      id: "sdc21r7",
      title: "OpenTSDB - A Distributed, Scalable Monitoring System - Homepage",
      author: "OpenTSDB",
      time: "",
      link: "https://opentsdb.net/",
    },
    {
      id: "sdc21r8",
      title: "Data model",
      author: "Prometheus",
      time: "",
      link: "https://prometheus.io/docs/concepts/data_model/",
    },
    {
      id: "sdc21r9",
      title: "Schema design for time-series data | Cloud Bigtable Documentation",
      author: "Google Cloud",
      time: "",
      link: "https://cloud.google.com/bigtable/docs/schema-design-time-series",
    },
    {
      id: "sdc21r10",
      title: "MetricsDB: TimeSeries Database for storing metrics at Twitter",
      author: "Twitter Blog",
      time: "",
      link: "https://blog.twitter.com/engineering/en_us/topics/infrastructure/2019/metricsdb.html",
    },
    {
      id: "sdc21r11",
      title: "Amazon Timestream",
      author: "Amazon Web Services",
      time: "",
      link: "https://aws.amazon.com/timestream/",
    },
    {
      id: "sdc21r12",
      title: "DB-Engines Ranking of time-series DBMS",
      author: "",
      time: "",
      link: "https://db-engines.com/en/ranking/time+series+dbms",
    },
    {
      id: "sdc21r13",
      title: "InfluxDB Homepage",
      author: "",
      time: "",
      link: "https://www.influxdata.com/",
    },
    {
      id: "sdc21r14",
      title: "etcd Homepage",
      author: "etcd",
      time: "",
      link: "https://etcd.io",
    },
    {
      id: "sdc21r15",
      title: "Service Discovery with Zookeeper",
      author: "",
      time: "",
      link: "https://cloud.spring.io/spring-cloud-zookeeper/1.2.x/multi/multi_spring-cloud-zookeeper-discovery.html",
    },
    {
      id: "sdc21r16",
      title: "Amazon CloudWatch",
      author: "Amazon Web Services",
      time: "",
      link: "https://aws.amazon.com/cloudwatch/",
    },
    {
      id: "sdc21r17",
      title: "Graphite Homepage",
      author: "",
      time: "",
      link: "https://graphiteapp.org/",
    },
    {
      id: "sdc21r18",
      title: "Push vs. Pull",
      author: "sflow Blog",
      time: "",
      link: "https://blog.sflow.com/2012/08/push-vs-pull.html",
    },
    {
      id: "sdc21r19",
      title: "Pull doesn't scale - or does it?",
      author: "Prometheus Blog",
      time: "",
      link: "https://prometheus.io/blog/2016/07/23/pull-does-not-scale-or-does-it/",
    },
    {
      id: "sdc21r20",
      title: "Monitoring Architecture",
      author: "Tech Hub",
      time: "",
      link: "https://developer.lightbend.com/guides/monitoring-at-scale/monitoring-architecture/architecture.html",
    },
    {
      id: "sdc21r21",
      title: "Push vs Pull in Monitoring Systems",
      author: "Giedrius Blog",
      time: "",
      link: "https://giedrius.blog/2019/05/11/push-vs-pull-in-monitoring-systems/",
    },
    {
      id: "sdc21r22",
      title: "Pushgateway",
      author: "Prometheus",
      time: "",
      link: "https://github.com/prometheus/pushgateway",
    },
    {
      id: "sdc21r23",
      title: "Building Applications with Serverless Architectures",
      author: "Amazon Web Services",
      time: "",
      link: "https://aws.amazon.com/lambda/serverless-architectures-learn-more/",
    },
    {
      id: "sdc21r24",
      title: "Gorilla: A Fast, Scalable, In-Memory Time Series Database",
      author: "VLDB",
      time: "",
      link: "https://www.vldb.org/pvldb/vol8/p1816-teller.pdf",
    },
    {
      id: "sdc21r25",
      title: "Why We're Building Flux, a New Data Scripting and Query Language",
      author: "Paul Dix",
      time: "",
      link: "https://www.influxdata.com/blog/why-were-building-flux-a-new-data-scripting-and-query-language/",
    },
    {
      id: "sdc21r26",
      title: "InfluxDB storage engine",
      author: "InfluxDB Docs",
      time: "",
      link: "https://docs.influxdata.com/influxdb/v2.0/reference/internals/storage-engine/",
    },
    {
      id: "sdc21r27",
      title: "YAML",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/YAML",
    },
    {
      id: "sdc21r28",
      title: "Grafana Demo",
      author: "",
      time: "",
      link: "https://play.grafana.org/",
    },
  ],
  sdc22: [
    {
      id: "sdc22r1",
      title: "Clickthrough rate (CTR): Definition",
      author: "",
      time: "",
      link: "https://support.google.com/google-ads/answer/2615875?hl=en",
    },
    {
      id: "sdc22r2",
      title: "Conversion rate: Definition",
      author: "",
      time: "",
      link: "https://support.google.com/google-ads/answer/2684489?hl=en",
    },
    {
      id: "sdc22r3",
      title: "OLAP functions",
      author: "Oracle Docs",
      time: "",
      link: "https://docs.oracle.com/database/121/OLAXS/olap_functions.htm#OLAXS169",
    },
    {
      id: "sdc22r4",
      title: "Display Advertising with Real-Time Bidding (RTB) and Behavioural Targeting",
      author: "Jun Wang et al.",
      time: "",
      link: "https://arxiv.org/pdf/1610.03013.pdf",
    },
    {
      id: "sdc22r5",
      title: "LanguageManual ORC",
      author: "Apache",
      time: "",
      link: "https://cwiki.apache.org/confluence/display/hive/languagemanual+orc",
    },
    {
      id: "sdc22r6",
      title: "Parquet",
      author: "databricks",
      time: "",
      link: "https://databricks.com/glossary/what-is-parquet",
    },
    {
      id: "sdc22r7",
      title: "What is avro",
      author: "IBM",
      time: "",
      link: "https://www.ibm.com/topics/avro",
    },
    {
      id: "sdc22r8",
      title: "Big Data",
      author: "DataKwery",
      time: "",
      link: "https://www.datakwery.com/techniques/big-data/",
    },
    {
      id: "sdc22r9",
      title: "DAG model",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Directed_acyclic_graph",
    },
    {
      id: "sdc22r10",
      title: "Java stream",
      author: "Oracle Docs",
      time: "",
      link: "https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html",
    },
    {
      id: "sdc22r11",
      title: "Understand star schema and the importance for Power BI",
      author: "Microsoft",
      time: "",
      link: "https://docs.microsoft.com/en-us/power-bi/guidance/star-schema",
    },
    {
      id: "sdc22r12",
      title: "Designing Data-Intensive Applications",
      author: "Martin Kleppmann",
      time: "2017",
      link: "https://www.oreilly.com/library/view/designing-data-intensive-applications/9781491903063/",
    },
    {
      id: "sdc22r13",
      title: "Apache Flink Homepage",
      author: "Apache Flink",
      time: "",
      link: "https://flink.apache.org/",
    },
    {
      id: "sdc22r14",
      title: "Lambda architecture",
      author: "databricks",
      time: "",
      link: "https://databricks.com/glossary/lambda-architecture",
    },
    {
      id: "sdc22r15",
      title: "Kappa architecture",
      author: "Hazelcast",
      time: "",
      link: "https://hazelcast.com/glossary/kappa-architecture/",
    },
    {
      id: "sdc22r16",
      title: "Designing Data-Intensive Applications",
      author: "Martin Kleppmann",
      time: "2017",
      link: "https://www.oreilly.com/library/view/designing-data-intensive-applications/9781491903063/",
    },
    {
      id: "sdc22r17",
      title: "End-to-end Exactly-once Aggregation Over Ad Streams",
      author: "Amit",
      time: "",
      link: "https://www.youtube.com/watch?v=hzxytnPcAUM",
    },
    {
      id: "sdc22r18",
      title: "Ad traffic quality",
      author: "",
      time: "",
      link: "https://www.google.com/ads/adtrafficquality",
    },
    {
      id: "sdc22r19",
      title: "An Overview of End-to-End Exactly-Once Processing in Apache Flink",
      author: "Apache Flink",
      time: "",
      link: "https://flink.apache.org/features/2018/03/01/end-to-end-exactly-once-apache-flink.html",
    },
    {
      id: "sdc22r20",
      title: "Understanding MapReduce in Hadoop",
      author: "Onesmus Mbaabu",
      time: "",
      link: "https://www.section.io/engineering-education/understanding-map-reduce-in-hadoop/",
    },
    {
      id: "sdc22r21",
      title: "Flink on Apache Yarn",
      author: "Apache",
      time: "",
      link: "https://ci.apache.org/projects/flink/flink-docs-release-1.13/docs/deployment/resource-providers/yarn/",
    },
    {
      id: "sdc22r22",
      title: "How data is distributed across a cluster (using virtual nodes)",
      author: "DataStax",
      time: "",
      link: "https://docs.datastax.com/en/cassandra-oss/3.0/cassandra/architecture/archDataDistributeDistribute.html",
    },
    {
      id: "sdc22r23",
      title: "Flink performance tuning",
      author: "Apache",
      time: "",
      link: "https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/tuning/",
    },
    {
      id: "sdc22r24",
      title: "ClickHouse Homepage",
      author: "ClickHouse",
      time: "",
      link: "https://clickhouse.com/",
    },
    {
      id: "sdc22r25",
      title: "Apache Druid Homepage",
      author: "Apache",
      time: "",
      link: "https://druid.apache.org/",
    },
    {
      id: "sdc22r26",
      title: "Real-Time Exactly-Once Ad Event Processing with Apache Flink, Kafka, and Pinot",
      author: "Uber Blog",
      time: "",
      link: "https://eng.uber.com/real-time-exactly-once-ad-event-processing/",
    },
  ],
  sdc23: [
    {
      id: "sdc23r1",
      title: "Microservices",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Microservices",
    },
    {
      id: "sdc23r2",
      title: "What Are The Benefits of Microservices Architecture?",
      author: "AppDynamics",
      time: "",
      link: "https://www.appdynamics.com/topics/benefits-of-microservices",
    },
    {
      id: "sdc23r3",
      title: "gRPC Introduction",
      author: "gRPC",
      time: "",
      link: "https://www.grpc.io/docs/what-is-grpc/introduction/",
    },
    {
      id: "sdc23r4",
      title: "Booking(.com) iOS app",
      author: "",
      time: "",
      link: "https://www.booking.com/",
    },
    {
      id: "sdc23r5",
      title: "Serializability",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Serializability",
    },
    {
      id: "sdc23r6",
      title: "Optimistic and pessimistic record locking",
      author: "IBM",
      time: "",
      link: "https://ibm.co/3Eb293O",
    },
    {
      id: "sdc23r7",
      title: "Optimistic concurrency control",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Optimistic_concurrency_control",
    },
    {
      id: "sdc23r8",
      title: "Change data capture",
      author: "Oracle",
      time: "",
      link: "https://docs.oracle.com/cd/B10500_01/server.920/a96520/cdc.htm",
    },
    {
      id: "sdc23r9",
      title: "Debizium Homepage",
      author: "Debezium",
      time: "",
      link: "https://debezium.io/",
    },
    {
      id: "sdc23r10",
      title: "Redis sink",
      author: "Debezium",
      time: "",
      link: "https://debezium.io/documentation/reference/1.5/operations/debezium-server.html#_redis_stream",
    },
    {
      id: "sdc23r11",
      title: "Monolithic Architecture",
      author: "Chris Richardson",
      time: "",
      link: "https://microservices.io/patterns/monolithic.html",
    },
    {
      id: "sdc23r12",
      title: "Two-phase commit protocol",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Two-phase_commit_protocol",
    },
    {
      id: "sdc23r13",
      title: "Saga",
      author: "Chris Richardson",
      time: "",
      link: "https://microservices.io/patterns/data/saga.html",
    },
  ],
  sdc24: [
    {
      id: "sdc24r1",
      title: "Number of Active Gmail Users",
      author: "FinancesOnline",
      time: "",
      link: "https://financesonline.com/number-of-active-gmail-users/",
    },
    {
      id: "sdc24r2",
      title: "Outlook",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Outlook.com",
    },
    {
      id: "sdc24r3",
      title: "How Many Emails Are Sent Per Day in 2021?",
      author: "",
      time: "",
      link: "https://review42.com/resources/how-many-emails-are-sent-per-day/",
    },
    {
      id: "sdc24r4",
      title: "RFC 1939 - Post Office Protocol - Version 3",
      author: "",
      time: "",
      link: "https://www.faqs.org/rfcs/rfc1939.html",
    },
    {
      id: "sdc24r5",
      title: "ActiveSync",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/ActiveSync",
    },
    {
      id: "sdc24r6",
      title: "Email attachment",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Email_attachment",
    },
    {
      id: "sdc24r7",
      title: "MIME",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/MIME",
    },
    {
      id: "sdc24r8",
      title: "Threading",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Conversation_threading",
    },
    {
      id: "sdc24r9",
      title: "IMAP LIST Extension for Special-Use Mailboxes",
      author: "DataTracker",
      time: "",
      link: "https://datatracker.ietf.org/doc/html/rfc6154",
    },
    {
      id: "sdc24r10",
      title: "Apache James Homepage",
      author: "Apache James",
      time: "",
      link: "https://james.apache.org/",
    },
    {
      id: "sdc24r11",
      title: "A JSON Meta Application Protocol (JMAP) Subprotocol for WebSocket",
      author: "",
      time: "",
      link: "https://tools.ietf.org/id/draft-ietf-jmap-websocket-07.html#RFC7692",
    },
    {
      id: "sdc24r12",
      title: "Cassandra Limitations",
      author: "",
      time: "",
      link: "https://cwiki.apache.org/confluence/display/CASSANDRA2/CassandraLimitations",
    },
    {
      id: "sdc24r13",
      title: "Inverted index",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Inverted_index",
    },
    {
      id: "sdc24r14",
      title: "Exponential backoff",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Exponential_backoff",
    },
    {
      id: "sdc24r15",
      title: "QQ Email System Optimization (in Chinese)",
      author: "",
      time: "",
      link: "https://www.slideshare.net/areyouok/06-qq-5431919",
    },
    {
      id: "sdc24r16",
      title: "IOPS",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/IOPS",
    },
    {
      id: "sdc24r17",
      title: "UUID and timeuuid types",
      author: "DataStax Docs",
      time: "",
      link: "https://docs.datastax.com/en/cql-oss/3.3/cql/cql_reference/uuid_type_r.html",
    },
    {
      id: "sdc24r18",
      title: "Message threading",
      author: "Jamie Zawinski",
      time: "",
      link: "https://www.jwz.org/doc/threading.html",
    },
    {
      id: "sdc24r19",
      title: "Global spam volume",
      author: "Statista",
      time: "",
      link: "https://www.statista.com/statistics/420391/spam-email-traffic-share/",
    },
    {
      id: "sdc24r20",
      title: "Warming up dedicated IP addresses",
      author: "Amazon Web Services",
      time: "",
      link: "https://docs.aws.amazon.com/ses/latest/dg/dedicated-ip-warming.html",
    },
    {
      id: "sdc24r21",
      title: "2018 Data Breach Investigations Report",
      author: "Verizon",
      time: "",
      link: "https://enterprise.verizon.com/resources/reports/DBIR_2018_Report.pdf",
    },
    {
      id: "sdc24r22",
      title: "Sender Policy Framework",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Sender_Policy_Framework",
    },
    {
      id: "sdc24r23",
      title: "DomainKeys Identified Mail",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/DomainKeys_Identified_Mail",
    },
    {
      id: "sdc24r24",
      title: "Domain-based Message Authentication, Reporting & Conformance",
      author: "",
      time: "",
      link: "https://dmarc.org/",
    },
    {
      id: "sdc24r25",
      title: "DB-Engines Ranking of Search Engines",
      author: "",
      time: "",
      link: "https://db-engines.com/en/ranking/search+engine",
    },
    {
      id: "sdc24r26",
      title: "Refactoring practice: build full-text search of QQ mailbox based on Tencent Cloud Elasticsearch",
      author: "ProgrammerSought",
      time: "",
      link: "https://www.programmersought.com/article/24097547237/",
    },
    {
      id: "sdc24r27",
      title: "Log-structured merge-tree",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Log-structured_merge-tree",
    },
    {
      id: "sdc24r28",
      title: "Microsoft Exchange Conference 2014 Search in Exchange",
      author: "YouTube",
      time: "",
      link: "https://www.youtube.com/watch?v=5EXGCSzzQak&t=2173s",
    },
    {
      id: "sdc24r29",
      title: "General Data Protection Regulation",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/General_Data_Protection_Regulation",
    },
    {
      id: "sdc24r30",
      title: "Lawful interception",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Lawful_interception",
    },
    {
      id: "sdc24r31",
      title: "Email safety",
      author: "Google Safety",
      time: "",
      link: "https://safety.google/intl/en_us/gmail/",
    },
  ],
  sdc25: [
    {
      id: "sdc25r1",
      title: "Fibre channel",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Fibre_Channel",
    },
    {
      id: "sdc25r2",
      title: "iSCSI",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/ISCSI",
    },
    {
      id: "sdc25r3",
      title: "Server Message Block",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Server_Message_Block",
    },
    {
      id: "sdc25r4",
      title: "Network File System",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Network_File_System",
    },
    {
      id: "sdc25r5",
      title: "Amazon S3 Strong Consistency",
      author: "Amazon Web Services",
      time: "",
      link: "https://aws.amazon.com/s3/consistency/",
    },
    {
      id: "sdc25r6",
      title: "Serial Attached SCSI",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Serial_Attached_SCSI",
    },
    {
      id: "sdc25r7",
      title: "AWS CLI ls command",
      author: "Amazon Web Services",
      time: "",
      link: "https://docs.aws.amazon.com/cli/latest/reference/s3/ls.html",
    },
    {
      id: "sdc25r8",
      title: "Amazon S3 Service Level Agreement",
      author: "Amazon Web Services",
      time: "",
      link: "https://aws.amazon.com/s3/sla/",
    },
    {
      id: "sdc25r9",
      title: "Ambry: LinkedIn's Scalable Geo-Distributed Object Store",
      author: "Shadi A. Noghabi et al.",
      time: "",
      link: "https://assured-cloud-computing.illinois.edu/files/2014/03/Ambry-LinkedIns-Scalable-GeoDistributed-Object-Store.pdf",
    },
    {
      id: "sdc25r10",
      title: "inode",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Inode",
    },
    {
      id: "sdc25r11",
      title: "Ceph's Rados Gateway",
      author: "Ceph Docs",
      time: "",
      link: "https://docs.ceph.com/en/pacific/radosgw/index.html",
    },
    {
      id: "sdc25r12",
      title: "grpc Homepage",
      author: "gRPC",
      time: "",
      link: "https://grpc.io/",
    },
    {
      id: "sdc25r13",
      title: "Paxos",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Paxos_(computer_science)",
    },
    {
      id: "sdc25r14",
      title: "Raft Homepage",
      author: "Raft",
      time: "",
      link: "https://raft.github.io/",
    },
    {
      id: "sdc25r15",
      title: "Consistent hashing",
      author: "Toptal",
      time: "",
      link: "https://www.toptal.com/big-data/consistent-hashing",
    },
    {
      id: "sdc25r16",
      title: "RocksDB",
      author: "Facebook",
      time: "",
      link: "https://github.com/facebook/rocksdb",
    },
    {
      id: "sdc25r17",
      title: "SSTable",
      author: "Igvita",
      time: "",
      link: "https://www.igvita.com/2012/02/06/sstable-and-log-structured-storage-leveldb/",
    },
    {
      id: "sdc25r18",
      title: "B+ tree",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/B%2B_tree",
    },
    {
      id: "sdc25r19",
      title: "SQLite Homepage",
      author: "SQLite",
      time: "",
      link: "https://www.sqlite.org/index.html",
    },
    {
      id: "sdc25r20",
      title: "Data Durability Calculation",
      author: "Backblaze",
      time: "",
      link: "https://www.backblaze.com/blog/cloud-storage-durability/",
    },
    {
      id: "sdc25r21",
      title: "Rack",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/19-inch_rack",
    },
    {
      id: "sdc25r22",
      title: "Erasure Coding",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Erasure_code",
    },
    {
      id: "sdc25r23",
      title: "Reed-Solomon error correction",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Reed%E2%80%93Solomon_error_correction",
    },
    {
      id: "sdc25r24",
      title: "Erasure Coding Demystified",
      author: "YouTube",
      time: "",
      link: "https://www.youtube.com/watch?v=Q5kVuM7zEUI",
    },
    {
      id: "sdc25r25",
      title: "Checksum",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Checksum",
    },
    {
      id: "sdc25r26",
      title: "Md5",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/MD5",
    },
    {
      id: "sdc25r27",
      title: "Sha1",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/SHA-1",
    },
    {
      id: "sdc25r28",
      title: "Hmac",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/HMAC",
    },
    {
      id: "sdc25r29",
      title: "TIMEUUID",
      author: "DataStax",
      time: "",
      link: "https://docs.datastax.com/en/cql-oss/3.3/cql/cql_reference/timeuuid_functions_r.html",
    },
  ],
  sdc26: [
    {
      id: "sdc26r1",
      title: "Redis Sorted Set source code",
      author: "Redis",
      time: "",
      link: "https://github.com/redis/redis/blob/unstable/src/t_zset.c",
    },
    {
      id: "sdc26r2",
      title: "Geekbang",
      author: "GeekBang",
      time: "",
      link: "https://static001.geekbang.org/resource/image/46/a9/46d283cd82c987153b3fe0c76dfba8a9.jpg",
    },
    {
      id: "sdc26r3",
      title: "Building real-time Leaderboard with Redis",
      author: "Sandeep Verma",
      time: "",
      link: "https://medium.com/@sandeep4.verma/building-real-time-leaderboard-with-redis-82c98aa47b9f",
    },
    {
      id: "sdc26r4",
      title: "Build a real-time gaming leaderboard with Amazon ElastiCache for Redis",
      author: "Amazon Web Services",
      time: "",
      link: "https://aws.amazon.com/blogs/database/building-a-real-time-gaming-leaderboard-with-amazon-elasticache-for-redis",
    },
    {
      id: "sdc26r5",
      title: "How we created a real-time Leaderboard for a million Users",
      author: "Juan Manuel Villegas",
      time: "",
      link: "https://levelup.gitconnected.com/how-we-created-a-real-time-leaderboard-for-a-million-users-555aaa3ccf7b",
    },
    {
      id: "sdc26r6",
      title: "Leaderboards",
      author: "RedisLabs",
      time: "",
      link: "https://redislabs.com/solutions/use-cases/leaderboards/",
    },
    {
      id: "sdc26r7",
      title: "Lambda",
      author: "Amazon Web Services",
      time: "",
      link: "https://aws.amazon.com/lambda/",
    },
    {
      id: "sdc26r8",
      title: "Google Cloud Functions",
      author: "Google Cloud",
      time: "",
      link: "https://cloud.google.com/functions",
    },
    {
      id: "sdc26r9",
      title: "Azure Functions",
      author: "Microsoft Azure",
      time: "",
      link: "https://azure.microsoft.com/en-us/services/functions/",
    },
    {
      id: "sdc26r10",
      title: "Info command",
      author: "Redis",
      time: "",
      link: "https://redis.io/commands/INFO",
    },
    {
      id: "sdc26r11",
      title: "Why redis cluster only have 16384 slots",
      author: "Stack Overflow",
      time: "",
      link: "https://stackoverflow.com/questions/36203532/why-redis-cluster-only-have-16384-slots",
    },
    {
      id: "sdc26r12",
      title: "Cyclic redundancy check",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Cyclic_redundancy_check",
    },
    {
      id: "sdc26r13",
      title: "Choosing your node size",
      author: "Amazon Web Services",
      time: "",
      link: "https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/nodes-select-size.html",
    },
    {
      id: "sdc26r14",
      title: "How fast is Redis?",
      author: "Redis",
      time: "",
      link: "https://redis.io/topics/benchmarks",
    },
    {
      id: "sdc26r15",
      title: "Using Global Secondary Indexes in DynamoDB",
      author: "Amazon Web Services",
      time: "",
      link: "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GSI.html.",
    },
    {
      id: "sdc26r16",
      title: "Leaderboard & Write Sharding",
      author: "DynamoDBGuide",
      time: "",
      link: "https://www.dynamodbguide.com/leaderboard-write-sharding/",
    },
  ],
  sdc27: [
    {
      id: "sdc27r1",
      title: "Payment system",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Payment_system",
    },
    {
      id: "sdc27r2",
      title: "AML/CFT",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Money_laundering",
    },
    {
      id: "sdc27r3",
      title: "Card scheme",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Card_scheme",
    },
    {
      id: "sdc27r4",
      title: "ISO 4217",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/ISO_4217",
    },
    {
      id: "sdc27r5",
      title: "Stripe API Reference",
      author: "Stripe",
      time: "",
      link: "https://stripe.com/docs/api",
    },
    {
      id: "sdc27r6",
      title: "Double-entry bookkeeping",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Double-entry_bookkeeping",
    },
    {
      id: "sdc27r7",
      title: "Books, an immutable double-entry accounting database service",
      author: "",
      time: "",
      link: "https://developer.squareup.com/blog/books-an-immutable-double-entry-accounting-database-service/",
    },
    {
      id: "sdc27r8",
      title: "Payment Card Industry Data Security Standard",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Payment_Card_Industry_Data_Security_Standard",
    },
    {
      id: "sdc27r9",
      title: "Tipalti Homepage",
      author: "Tipalti",
      time: "",
      link: "https://tipalti.com/",
    },
    {
      id: "sdc27r10",
      title: "Nonce",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Cryptographic_nonce",
    },
    {
      id: "sdc27r11",
      title: "Webhooks",
      author: "Stripe",
      time: "",
      link: "https://stripe.com/docs/webhooks",
    },
    {
      id: "sdc27r12",
      title: "Customize your success page",
      author: "Stripe",
      time: "",
      link: "https://stripe.com/docs/payments/checkout/custom-success-page",
    },
    {
      id: "sdc27r13",
      title: "3D Secure",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/3-D_Secure",
    },
    {
      id: "sdc27r14",
      title: "Kafka Connect Deep Dive - Error Handling and Dead Letter Queues",
      author: "Confluent",
      time: "",
      link: "https://www.confluent.io/blog/kafka-connect-deep-dive-error-handling-dead-letter-queues/",
    },
    {
      id: "sdc27r15",
      title: "Reliable Processing in a Streaming Payment System",
      author: "YouTube",
      time: "",
      link: "https://www.youtube.com/watch?v=5TD8m7w1xE0&list=PLLEUtp5eGr7Dz3fWGUpiSiG3d_WgJe-KJ",
    },
    {
      id: "sdc27r16",
      title: "Chain Services with Exactly-Once Guarantees",
      author: "Confluent",
      time: "",
      link: "https://www.confluent.io/blog/chain-services-exactly-guarantees/",
    },
    {
      id: "sdc27r17",
      title: "Exponential backoff",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Exponential_backoff",
    },
    {
      id: "sdc27r18",
      title: "Idempotence",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Idempotence",
    },
    {
      id: "sdc27r19",
      title: "Stripe idempotent requests",
      author: "Stripe",
      time: "",
      link: "https://stripe.com/docs/api/idempotent_requests",
    },
    {
      id: "sdc27r20",
      title: "Idempotency",
      author: "PayPal",
      time: "",
      link: "https://developer.paypal.com/docs/platforms/develop/idempotency/",
    },
    {
      id: "sdc27r21",
      title: "Paxos",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Paxos_(computer_science)",
    },
    {
      id: "sdc27r22",
      title: "Raft Homepage",
      author: "Raft",
      time: "",
      link: "https://raft.github.io/",
    },
    {
      id: "sdc27r23",
      title: "YugabyteDB Homepage",
      author: "",
      time: "",
      link: "https://www.yugabyte.com/",
    },
    {
      id: "sdc27r24",
      title: "Cockroachdb Homepage",
      author: "Cockroach Labs",
      time: "",
      link: "https://www.cockroachlabs.com/",
    },
    {
      id: "sdc27r25",
      title: "What is DDoS attack",
      author: "Cloudflare",
      time: "",
      link: "https://www.cloudflare.com/learning/ddos/what-is-a-ddos-attack/",
    },
    {
      id: "sdc27r26",
      title: "How Payment Gateways Can Detect and Prevent Online Fraud",
      author: "Chargebee Blog",
      time: "",
      link: "https://www.chargebee.com/blog/optimize-online-billing-stop-online-fraud/",
    },
    {
      id: "sdc27r27",
      title: "Advanced Technologies for Detecting and Preventing Fraud at Uber",
      author: "Uber Blog",
      time: "",
      link: "https://eng.uber.com/advanced-technologies-detecting-preventing-fraud-uber/",
    },
    {
      id: "sdc27r28",
      title: "Re-Architecting Cash and Digital Wallet Payments for India with Uber Engineering",
      author: "Uber Blog",
      time: "",
      link: "https://eng.uber.com/india-payments/",
    },
    {
      id: "sdc27r29",
      title: "Scaling Airbnb's Payment Platform",
      author: "Airbnb Blog",
      time: "",
      link: "https://medium.com/airbnb-engineering/scaling-airbnbs-payment-platform-43ebfc99b324",
    },
    {
      id: "sdc27r30",
      title: "Payments Integration at Uber: A Case Study",
      author: "Uber Engineering",
      time: "",
      link: "https://www.youtube.com/watch?v=yooCE5B0SRA",
    },
  ],
  sdc28: [
    {
      id: "sdc28r1",
      title: "Transactional guarantees",
      author: "Oracle Docs",
      time: "",
      link: "https://docs.oracle.com/cd/E17275_01/html/programmer_reference/rep_trans.html",
    },
    {
      id: "sdc28r2",
      title: "TPC-E Top Price/Performance Results: ",
      author: "TPC",
      time: "",
      link: "https://tpc.org/tpce/results/tpce_price_perf_results5.asp?resulttype=all",
    },
    {
      id: "sdc28r3",
      title: "ISO 4217 CURRENCY CODES",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/ISO_4217",
    },
    {
      id: "sdc28r4",
      title: "Apache Zookeeper Homepage",
      author: "Apache Zookeeper",
      time: "",
      link: "https://zookeeper.apache.org/",
    },
    {
      id: "sdc28r5",
      title: "Designing Data-Intensive Applications",
      author: "Martin Kleppmann",
      time: "2017",
      link: "https://www.oreilly.com/library/view/designing-data-intensive-applications/9781491903063/",
    },
    {
      id: "sdc28r6",
      title: "X/Open XA",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/X/Open_XA",
    },
    {
      id: "sdc28r7",
      title: "Compensating transaction",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Compensating_transaction",
    },
    {
      id: "sdc28r8",
      title: "SAGAS, HectorGarcia-Molina",
      author: "Cornell CS",
      time: "",
      link: "https://www.cs.cornell.edu/andru/cs711/2002fa/reading/sagas.pdf",
    },
    {
      id: "sdc28r9",
      title: "Domain-Driven Design: Tackling Complexity in the Heart of Software",
      author: "Eric Evans",
      time: "2003",
      link: "https://www.oreilly.com/library/view/domain-driven-design-tackling/0321125215/",
    },
    {
      id: "sdc28r10",
      title: "Apache Kafka Homepage",
      author: "Apache Kafka",
      time: "",
      link: "https://kafka.apache.org/",
    },
    {
      id: "sdc28r11",
      title: "CQRS",
      author: "Martin Fowler",
      time: "",
      link: "https://martinfowler.com/bliki/CQRS.html",
    },
    {
      id: "sdc28r12",
      title: "Comparing Random and Sequential Access in Disk and Memory",
      author: "",
      time: "",
      link: "https://deliveryimages.acm.org/10.1145/1570000/1563874/jacobs3.jpg",
    },
    {
      id: "sdc28r13",
      title: "mmap",
      author: "",
      time: "",
      link: "https://man7.org/linux/man-pages/man2/mmap.2.html",
    },
    {
      id: "sdc28r14",
      title: "SQLite Homepage",
      author: "SQLite",
      time: "",
      link: "https://www.sqlite.org/index.html",
    },
    {
      id: "sdc28r15",
      title: "RocksDB Homepage",
      author: "RocksDB",
      time: "",
      link: "https://rocksdb.org/",
    },
    {
      id: "sdc28r16",
      title: "Apache Hadoop Homepage",
      author: "Apache Hadoop",
      time: "",
      link: "https://hadoop.apache.org/",
    },
    {
      id: "sdc28r17",
      title: "Raft Homepage",
      author: "Raft",
      time: "",
      link: "https://raft.github.io/",
    },
    {
      id: "sdc28r18",
      title: "Reverse proxy",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Reverse_proxy",
    },
  ],
  sdc29: [
    {
      id: "sdc29r1",
      title: "LMAX exchange was famous for its open-source Disruptor",
      author: "",
      time: "",
      link: "https://www.lmax.com/exchange",
    },
    {
      id: "sdc29r2",
      title: "IEX attracts investors by 'playing fair', also is the 'Flash Boys Exchange'",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/IEX",
    },
    {
      id: "sdc29r3",
      title: "NYSE matched volume",
      author: "NYSE",
      time: "",
      link: "https://www.nyse.com/markets/us-equity-volumes",
    },
    {
      id: "sdc29r4",
      title: "HKEX daily trading volume",
      author: "",
      time: "",
      link: "https://www.hkex.com.hk/Market-Data/Statistics/Consolidated-Reports/Securities-Statistics-Archive/Trading_Value_Volume_And_Number_Of_Deals?sc_lang=en#select1=0",
    },
    {
      id: "sdc29r5",
      title: "All of the World's Stock Exchanges by Size",
      author: "",
      time: "",
      link: "https://money.visualcapitalist.com/all-of-the-worlds-stock-exchanges-by-size/",
    },
    {
      id: "sdc29r6",
      title: "Denial of service attack",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Denial-of-service_attack",
    },
    {
      id: "sdc29r7",
      title: "Market impact",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Market_impact",
    },
    {
      id: "sdc29r8",
      title: "Fix trading",
      author: "",
      time: "",
      link: "https://www.fixtrading.org/",
    },
    {
      id: "sdc29r9",
      title: "Event Sourcing",
      author: "Martin Fowler",
      time: "",
      link: "https://martinfowler.com/eaaDev/EventSourcing.html",
    },
    {
      id: "sdc29r10",
      title: "CME Co-Location and Data Center Services",
      author: "CME Group",
      time: "",
      link: "https://www.cmegroup.com/trading/colocation/co-location-services.html",
    },
    {
      id: "sdc29r11",
      title: "Epoch",
      author: "",
      time: "",
      link: "https://www.epoch101.com/",
    },
    {
      id: "sdc29r12",
      title: "Order book",
      author: "",
      time: "",
      link: "https://www.investopedia.com/terms/o/order-book.asp",
    },
    {
      id: "sdc29r13",
      title: "Order book",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Order_book",
    },
    {
      id: "sdc29r14",
      title: "How to Build a Fast Limit Order Book",
      author: "",
      time: "",
      link: "https://web.archive.org/web/20110219163448/http://howtohft.wordpress.com/2011/02/15/how-to-build-a-fast-limit-order-book/",
    },
    {
      id: "sdc29r15",
      title: "Developing with kdb+ and the q language",
      author: "",
      time: "",
      link: "https://code.kx.com/q/",
    },
    {
      id: "sdc29r16",
      title: "Latency Numbers Every Programmer Should Know",
      author: "",
      time: "",
      link: "https://gist.github.com/jboner/2841832",
    },
    {
      id: "sdc29r17",
      title: "mmap",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Memory_map",
    },
    {
      id: "sdc29r18",
      title: "Context switch",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Context_switch",
    },
    {
      id: "sdc29r19",
      title: "Reliable User Datagram Protocol",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Reliable_User_Datagram_Protocol",
    },
    {
      id: "sdc29r20",
      title: "Aeron",
      author: "",
      time: "",
      link: "https://github.com/real-logic/aeron/wiki/Design-Overview",
    },
    {
      id: "sdc29r21",
      title: "Chaos engineering",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/Chaos_engineering",
    },
    {
      id: "sdc29r22",
      title: "Raft Homepage",
      author: "Raft",
      time: "",
      link: "https://raft.github.io/",
    },
    {
      id: "sdc29r23",
      title: "Designing for Understandability: the Raft Consensus Algorithm",
      author: "Raft",
      time: "",
      link: "https://raft.github.io/slides/uiuc2016.pdf",
    },
    {
      id: "sdc29r24",
      title: "Supported Matching Algorithms",
      author: "CME Group",
      time: "",
      link: "https://www.cmegroup.com/confluence/display/EPICSANDBOX/Supported+Matching+Algorithms",
    },
    {
      id: "sdc29r25",
      title: "Dark pool",
      author: "Investopedia",
      time: "",
      link: "https://www.investopedia.com/terms/d/dark-pool.asp",
    },
    {
      id: "sdc29r26",
      title: "HdrHistogram: A High Dynamic Range Histogram",
      author: "",
      time: "",
      link: "https://hdrhistogram.org/",
    },
    {
      id: "sdc29r27",
      title: "HotSpot (virtual machine)",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/HotSpot_(virtual_machine)",
    },
    {
      id: "sdc29r28",
      title: "Cache line padding",
      author: "Trisha Gee",
      time: "",
      link: "https://trishagee.com/2011/07/22/dissecting_the_disruptor_why_its_so_fast_part_two__magic_cache_line_padding/",
    },
    {
      id: "sdc29r29",
      title: "NACK-Oriented Reliable Multicast",
      author: "Wikipedia",
      time: "",
      link: "https://en.wikipedia.org/wiki/NACK-Oriented_Reliable_Multicast",
    },
    {
      id: "sdc29r30",
      title: "AWS Coinbase Case Study",
      author: "Amazon Web Services",
      time: "",
      link: "https://aws.amazon.com/solutions/case-studies/coinbase/",
    },
  ],
}

export default bibItems;
