/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  docs: [
    'intro',
    {
      type: 'category',
      label: 'Books',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Algorithm Design Manual',
          collapsed: true,
          items: [
            'books/algorithm-design-manual/lecture-notes',
            'books/algorithm-design-manual/exercises-and-solutions',
            {
              type: 'category',
              label: 'Book Notes',
              collapsed: true,
              items: [
                'books/algorithm-design-manual/book-notes/introduction-to-algorithm-design',
                'books/algorithm-design-manual/book-notes/algorithm-analysis',
                'books/algorithm-design-manual/book-notes/data-structures',
                'books/algorithm-design-manual/book-notes/sorting',
                'books/algorithm-design-manual/book-notes/divide-and-conquer',
                'books/algorithm-design-manual/book-notes/hashing-and-randomized-algorithms',
                'books/algorithm-design-manual/book-notes/graph-traversal',
                'books/algorithm-design-manual/book-notes/weighted-graph-algorithms',
                'books/algorithm-design-manual/book-notes/combinatorial-search',
                'books/algorithm-design-manual/book-notes/dynamic-programming',
                'books/algorithm-design-manual/book-notes/np-completeness',
                'books/algorithm-design-manual/book-notes/dealing-with-hard-problems',
                'books/algorithm-design-manual/book-notes/how-to-design-algorithms',
              ]
            },
          ]
        },
        {
          type: 'category',
          label: 'Nand to Tetris',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'books/nand-to-tetris/index'
          },
          items: [
            'books/nand-to-tetris/boolean-logic',
            'books/nand-to-tetris/boolean-arithmetic',
            'books/nand-to-tetris/memory',
            'books/nand-to-tetris/machine-language',
            'books/nand-to-tetris/computer-architecture',
            'books/nand-to-tetris/assembler',
            'books/nand-to-tetris/vm-processing',
            'books/nand-to-tetris/vm-control',
            'books/nand-to-tetris/high-level-language',
            'books/nand-to-tetris/compiler-syntax-analysis',
            'books/nand-to-tetris/compiler-code-generation',
            'books/nand-to-tetris/operating-system',
            'books/nand-to-tetris/more-fun-to-go',
            'books/nand-to-tetris/appendices',
          ]
        },
      ]
    },
    {
      type: 'category',
      label: 'Course Notes',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Development and Engineering',
          collapsed: true,
          items: [
            {
              type: 'category',
              label: 'MIT Missing Semester',
              link: {
                type: 'doc',
                id: 'course-notes/development-and-engineering/mit-missing-semester/index'
              },
              items: [
                'course-notes/development-and-engineering/mit-missing-semester/2020',
                'course-notes/development-and-engineering/mit-missing-semester/2019',
              ]
            },
            {
              type: 'category',
              label: 'Express',
              items: [
                'course-notes/development-and-engineering/express/just-express',
              ]
            },
            {
              type: 'category',
              label: 'React',
              items: [
                'course-notes/development-and-engineering/react/react-from-the-beginning',
              ]
            },
            'course-notes/development-and-engineering/jsnad/jsnad-course-notes',
            'course-notes/development-and-engineering/jsnsd/jsnsd-course-notes',
          ]
        },
        {
          type: 'category',
          label: 'Computer Science',
          collapsed: true,
          items: [
            {
              type: 'category',
              label: 'Teach Yourself CS',
              link: {
                type: 'doc',
                id: 'course-notes/computer-science/teach-yourself-cs/index'
              },
              items: [
                
              ]
            },
          ]
        },
      ]
    },
    'reference-list',
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
