/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  docs: [
    'intro',
    {
      type: 'category',
      label: 'Algorithm Design Manual',
      collapsed: true,
      items: [
        'algorithm-design-manual/algorithms-catalog',
        'algorithm-design-manual/algorithms-code',
        'algorithm-design-manual/miscellany',
        {
          type: 'category',
          label: 'Exercises and Solutions',
          collapsed: true,
          items: [
            'algorithm-design-manual/exercises-and-solutions/introduction-to-algorithm-design',
            'algorithm-design-manual/exercises-and-solutions/algorithm-analysis',
            'algorithm-design-manual/exercises-and-solutions/data-structures',
            'algorithm-design-manual/exercises-and-solutions/sorting',
            'algorithm-design-manual/exercises-and-solutions/divide-and-conquer',
            'algorithm-design-manual/exercises-and-solutions/hashing-and-randomized-algorithms',
            'algorithm-design-manual/exercises-and-solutions/graph-traversal',
            'algorithm-design-manual/exercises-and-solutions/weighted-graph-algorithms',
            'algorithm-design-manual/exercises-and-solutions/combinatorial-search',
            'algorithm-design-manual/exercises-and-solutions/dynamic-programming',
            'algorithm-design-manual/exercises-and-solutions/np-completeness',
            'algorithm-design-manual/exercises-and-solutions/dealing-with-hard-problems',
            'algorithm-design-manual/exercises-and-solutions/how-to-design-algorithms',
          ]
        },
        {
          type: 'category',
          label: 'Book Notes',
          collapsed: true,
          items: [
            'algorithm-design-manual/book-notes/introduction-to-algorithm-design',
            'algorithm-design-manual/book-notes/algorithm-analysis',
            'algorithm-design-manual/book-notes/data-structures',
            'algorithm-design-manual/book-notes/sorting',
            'algorithm-design-manual/book-notes/divide-and-conquer',
            'algorithm-design-manual/book-notes/hashing-and-randomized-algorithms',
            'algorithm-design-manual/book-notes/graph-traversal',
            'algorithm-design-manual/book-notes/weighted-graph-algorithms',
            'algorithm-design-manual/book-notes/combinatorial-search',
            'algorithm-design-manual/book-notes/dynamic-programming',
            'algorithm-design-manual/book-notes/np-completeness',
            'algorithm-design-manual/book-notes/dealing-with-hard-problems',
            'algorithm-design-manual/book-notes/how-to-design-algorithms',
          ]
        },
        {
          type: 'category',
          label: 'Lecture Notes',
          link: {
            type: 'doc',
            id: 'algorithm-design-manual/lecture-notes/index'
          },
          collapsed: true,
          items: [
            'algorithm-design-manual/lecture-notes/L1',
            'algorithm-design-manual/lecture-notes/L2',
            'algorithm-design-manual/lecture-notes/L3',
            'algorithm-design-manual/lecture-notes/L4',
            'algorithm-design-manual/lecture-notes/L5',
            'algorithm-design-manual/lecture-notes/L6',
            'algorithm-design-manual/lecture-notes/L7',
            'algorithm-design-manual/lecture-notes/L8',
            'algorithm-design-manual/lecture-notes/L9',
            'algorithm-design-manual/lecture-notes/L10',
            'algorithm-design-manual/lecture-notes/L11',
            'algorithm-design-manual/lecture-notes/L12',
            'algorithm-design-manual/lecture-notes/L13',
            'algorithm-design-manual/lecture-notes/L14',
            'algorithm-design-manual/lecture-notes/L15',
            'algorithm-design-manual/lecture-notes/L16',
            'algorithm-design-manual/lecture-notes/L17',
            'algorithm-design-manual/lecture-notes/L18',
            'algorithm-design-manual/lecture-notes/L19',
            'algorithm-design-manual/lecture-notes/L20',
            'algorithm-design-manual/lecture-notes/L21',
            'algorithm-design-manual/lecture-notes/L22',
            'algorithm-design-manual/lecture-notes/L23',
            'algorithm-design-manual/lecture-notes/L24',
            'algorithm-design-manual/lecture-notes/L25',
            'algorithm-design-manual/lecture-notes/L26',
          ]
        },
      ]
    },
    {
      type: 'category',
      label: 'C Programming Language',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Book Notes',
          collapsed: true,
          items: [
            'c-programming-language/book-notes/introduction',
            'c-programming-language/book-notes/a-tutorial-introduction',
            'c-programming-language/book-notes/types-operators-expressions',
            'c-programming-language/book-notes/control-flow',
            'c-programming-language/book-notes/functions-program-structures',
            'c-programming-language/book-notes/pointers-arrays',
            'c-programming-language/book-notes/structures',
            'c-programming-language/book-notes/input-output',
            'c-programming-language/book-notes/unix-system-interface',
            'c-programming-language/book-notes/appendix-a-reference-manual',
            'c-programming-language/book-notes/appendix-b-standard-library',
            'c-programming-language/book-notes/appendix-c-summary-of-changes'
          ]
        },
        {
          type: 'category',
          label: 'Exercises and Solutions',
          collapsed: true,
          items: [
            'c-programming-language/exercises-and-solutions/a-tutorial-introduction',
            'c-programming-language/exercises-and-solutions/types-operators-expressions',
            'c-programming-language/exercises-and-solutions/control-flow',
            'c-programming-language/exercises-and-solutions/functions-program-structures',
            'c-programming-language/exercises-and-solutions/pointers-arrays',
            'c-programming-language/exercises-and-solutions/structures',
            'c-programming-language/exercises-and-solutions/input-output',
            'c-programming-language/exercises-and-solutions/unix-system-interface',
          ]
        },
        {
          type: 'category',
          label: 'First Edition',
          collapsed: true,
          items: [
            'c-programming-language/first-edition/introduction',
            'c-programming-language/first-edition/a-tutorial-introduction',
            'c-programming-language/first-edition/types-operators-expressions',
            'c-programming-language/first-edition/control-flow',
            'c-programming-language/first-edition/functions-program-structures',
            'c-programming-language/first-edition/pointers-arrays',
            'c-programming-language/first-edition/structures',
            'c-programming-language/first-edition/input-output',
            'c-programming-language/first-edition/unix-system-interface',
          ]
        },
      ]
    },
    {
      type: 'category',
      label: 'Nand to Tetris',
      collapsed: true,
      items: [
        'nand-to-tetris/introduction',
        'nand-to-tetris/boolean-logic',
        'nand-to-tetris/boolean-arithmetic',
        'nand-to-tetris/memory',
        'nand-to-tetris/machine-language',
        'nand-to-tetris/computer-architecture',
        'nand-to-tetris/assembler',
        'nand-to-tetris/vm-processing',
        'nand-to-tetris/vm-control',
        'nand-to-tetris/high-level-language',
        'nand-to-tetris/compiler-syntax-analysis',
        'nand-to-tetris/compiler-code-generation',
        'nand-to-tetris/operating-system',
        'nand-to-tetris/more-fun-to-go',
        'nand-to-tetris/appendices',
      ]
    },
    {
      type: 'category',
      label: 'System Design',
      collapsed: true,
      items: [
        "system-design/c0",
        "system-design/c1",
        "system-design/c2",
        "system-design/c3",
        "system-design/c4",
        "system-design/c5",
        "system-design/c6",
        "system-design/c7",
        "system-design/c8",
        "system-design/c9",
        "system-design/c10",
        "system-design/c11",
        "system-design/c12",
        "system-design/c13",
        "system-design/c14",
        "system-design/c15",
        "system-design/c16",
        "system-design/c17",
        "system-design/c18",
        "system-design/c19",
        "system-design/c20",
        "system-design/c21",
        "system-design/c22",
        "system-design/c23",
        "system-design/c24",
        "system-design/c25",
        "system-design/c26",
        "system-design/c27",
        "system-design/c28",
        "system-design/c29",
        "system-design/c30",
      ]
    },
    'reference-list',
  ],
};

module.exports = sidebars;
